Add getRelationTypeDefinition methods
octobercms/library pull request #460
Opened 2020-02-06 13:04 UTC by Flynsarmy

Rather than read the relation arrays directly, use a methods to retrieve the list of defined relations. These overrideable methods are useful for creating relations on the fly based on data in your model. Fixes  https://github.com/octobercms/october/issues/4930

2020-02-16 09:06 UTC, bennothommo commented
@Flynsarmy could you provide some unit tests for this functionality, to give us a clearer idea of the potential use cases for this change?

2020-02-18 04:25 UTC, Flynsarmy commented
Tests added

2020-02-28 07:39 UTC, bennothommo commented
@Flynsarmy thanks for that. However, after looking at it a bit more, I feel it is a bit more verbose than just querying the arrays. @LukeTowers @w20k any thoughts on this?

2020-02-28 09:31 UTC, Flynsarmy commented
It's useful for overriding what relations are defined based on data in the model. You can't do that easily by modifying the arrays directly.

2020-07-10 00:22 UTC, Flynsarmy commented
Ping

2020-09-09 00:27 UTC, Flynsarmy commented
Ping

2020-09-09 02:16 UTC, bennothommo commented
@LukeTowers @daftspunk I'm happy to merge this, unless you have any objections?

2020-11-09 02:33 UTC, Flynsarmy commented
Ping

2021-01-08 05:54 UTC, bennothommo requested changes

2021-01-08 05:54 UTC, bennothommo commented on src/Database/Concerns/HasRelationships.php
> +     * @return array
@Flynsarmy your tests indicate that a string can be returned here, if someone is using the short-hand version of defining a relation. It also would return `null` if the definition type or name specified did not exist.
```suggestion
     * @return array|string|null
```

2021-01-08 05:54 UTC, bennothommo commented on src/Database/Concerns/HasRelationships.php
> +     * @return array
Could you also add a test case that shows an array being returned, just to tick that off as being tested?

2021-01-18 05:12 UTC, Flynsarmy commented
Added the extra test and updated the method annotation. Back to you @bennothommo

2021-01-22 07:29 UTC, merged

2021-01-22 07:31 UTC, bennothommo commented
@Flynsarmy could you provide a PR to the docs to demonstrate these new methods?